[project]
name = "text2tabular"
version = "0.1.0"
description = "Framework for reconstructing research data"
authors = [
    {name = "Jonas Gottal"}
]
packages = [{ include = "text2tabular", from = "src" }]
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "matplotlib (>=3.9.4,<4.0.0)",
    "numpy (>=2.0.2,<3.0.0)",
    "pandas (>=2.2.3,<3.0.0)",
    "plotly (>=6.0.1,<7.0.0)",
    "scikit-learn (>=1.6.1,<2.0.0)",
    "scipy (>=1.13.1,<2.0.0)",
    "seaborn (>=0.13.2,<0.14.0)",
    "statsmodels (>=0.14.4,<0.15.0)",
    "pydantic (>=2.11.4,<3.0.0)",
    "pymupdf4llm (>=0.0.24,<0.0.25)",
    "tenacity (>=9.1.2,<10.0.0)",
    "dotenv (>=0.9.9,<0.10.0)",
    "openai (>=1.78.1,<2.0.0)",
    "rdata (>=0.11.2,<0.12.0)",
    "camelot-py (>=1.0.0,<2.0.0)",
    "pymupdf (>=1.26.0,<2.0.0)",
    "pdf2image (>=1.17.0,<2.0.0)",
    "transformers (>=4.52.4,<5.0.0)",
    "torch (>=2.7.0,<3.0.0)",
    "gmft (>=0.4.1,<0.5.0)",
    "torchvision (>=0.22.0,<0.23.0)",
    "gmft-pymupdf @ git+https://github.com/conjuncts/gmft_pymupdf.git",
    "xlrd (>=2.0.2,<3.0.0)",
    "urllib3 (<2.0)",
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.group.dev.dependencies]
ipykernel = "^6.29.5"
pytest = "^8.3.5"
jupyter = "^1.1.1"


